;
; "The Gemini Nebula"
; by Dave Seidel
;
; A variation on La Monte Young's "The Prime Time Twins in the Ranges 576 to 448; 144 to 112; 72 to 56; 36 to 28; with the Range Limits 576, 448, 288, 224, 144, 56, and 28".
; 
; For La Monte Young in his 70th year.
; 
; Originally published in 2005, revised 2008.
; 
; Copyright 2005,2008 Dave Seidel. Licensed to the public under http://creativecommons.org/licenses/by/3.0/ verify at http://mysterybear.net/files/GeminiNebula.xml
;
; Generated by blue 0.122.0 (http://csounds.com/stevenyi/blue/index.html)
;

<CsoundSynthesizer>

<CsInstruments>
sr=88200
ksmps=1
nchnls=2

giTblSz	init	1048576

; sine wave table
gifn1	ftgen	1, 0, giTblSz, 10, 1




	opcode yipan,aa,ia

iSpace,aout	xin
iSpace		=	iSpace * 3.14159265359 * .5
krtl		= 	sqrt(2) / 2 * (cos(iSpace) + sin(iSpace))
krtr		= 	sqrt(2) / 2 * (cos(iSpace) - sin(iSpace))
aLeft		=	aout * krtl
aRight		=	aout * krtr
		xout	aLeft, aRight


	endop


	instr 1	;simple oscillator (freq)
idur	=	p3			; duration
iamp	=	p4			; amplitude
ifn	=	p5			; function table number (waveform)
ifreq	=	p6			; frequency
ilr	=	p7			; pan: -1.0  <-> +1.0
kenv	linen	iamp, 5, idur, 5
asig	poscil3	kenv, ifreq, ifn
;asig	dcblock	asig
al, ar	yipan	ilr, asig
	outc	al, ar

	endin


</CsInstruments>

<CsScore>









i1	40.909092	225	3000	1	244.21875	1
i1	61.36364	204.5454559326	3000	1	245.15625	-1
i1	81.818184	225	3000	1	252.1875	1
i1	102.27273	204.5454559326	3000	1	254.0625	-1
i1	122.72728	225	3000	1	256.875	1
i1	143.18182	204.5454559326	3000	1	260.625	-1
i1	163.63637	225	3000	1	263.4375	1
i1	184.09091	204.5454559326	3000	1	265.3125	-1
i1	204.54546	225	3000	1	266.71875	1
i1	225.0	204.5454559326	3000	1	267.65625	-1
i1	40.909092	225	3000	1	425.625	-1
i1	61.36364	204.5454559326	3000	1	429.375	1
i1	81.818184	225	3000	1	432.1875	-1
i1	102.27273	204.5454559326	3000	1	434.0625	1
i1	122.72728	306.8181762695	3000	1	435.0	-1
i1	143.18182	245.4545593262	3000	1	442.5	-1
i1	163.63637	184.0909118652	3000	1	448.125	-1
i1	184.09091	163.6363677979	3000	1	451.875	1
i1	204.54546	184.0909118652	3000	1	457.5	1
i1	225.0	204.5454559326	3000	1	465.0	1
i1	0.0	450	2500	1	240.0	0
i1	20.454546	429.5454711914	2500	1	270.0	0
i1	20.454546	429.5454711914	2500	1	420.0	0
i1	0.0	450	2500	1	480.0	0
e

</CsScore>

</CsoundSynthesizer>