#!/usr/bin/env bash

SCRIPTHOME=$(dirname $(readlink -f $0))

if [ $# -lt 4 ]; then
  echo "usage: convolve INPUT_FILE IMPULSE_FILE GAIN_ADJUST OUTPUT_FILE"
  exit 1
fi

INFILE=$1
IRFILE=$2
GAIN=$3
OUTFILE=$4

csound -m0 -d --omacro:INFILE=${INFILE} --omacro:IRFILE=${IRFILE} --omacro:GAIN=${GAIN} -W -R -3 -o $OUTFILE ${SCRIPTHOME}/convolver.csd

